version: "3.8"
services:
  mysql:
    platform: linux/x86_64
    image: library/mysql:8.0.28
    container_name: mini-firfin-mysql
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 4g
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: firfin
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci"]

  redis:
    platform: linux/x86_64
    image: library/redis:7.2.1
    container_name: mini-firfin-redis
    deploy:
      resources:
        limits:
          memory: 2g
    restart: always
    ports:
      - 6379:6379