spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

  # 과제 실행 단순화를 위해 추가함
  sql:
    init:
      mode: always

  # 과제 단순화를 위해 공통 설정에 추가
  data:
    redis:
      port: 6379
      host: localhost
      lettuce:
        pool:
          max-active: 4