# TODO: 진짜 prod 생기면 url 수정하고, username / password 수정해야 함
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/firfin?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      # validate여야 하지만 과제 편의성을 위해 update로 둠
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comment: false